# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6dbb014db1fec13955f84fac7f989cbf982e3097f579397d3dce51eab64d0eb9791acc147c7d972ad164b1e4a19df1a84843faeef7355c84cd1c0d28f93fc625

test:
  secret_key_base: 723a8bb0db61d08a92edc4935eb1f6d9b63bd714ff891b3d363cb9d12307692b4dc5e68dad68b08beb69c214bdfe46f3e211ede4cf6497a35edf17341f9da231

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
